name: Artifact1

on: [push]

env:

  ARTIFACT_NAME: myarifact

  job:
    main:
      runs-on: windows-latest
      steps:
       -name: check out the code
        uses: actions/checkout@v2
       -name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
  
